server:
  port: 8081
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Blog
    username: root
    password: Root@123
    drive-class-name: com.mysql.cj.jdbc.Driver
        
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
                
