server:
  port: 8082
  error:
    include-message: always
  
spring:
  application:
    name: Hotel-Service
  
  data:
    elasticsearch:
      cluster-names: elasticsearch
      cluster-node: localhost:9500
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      